// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// QueuewatchMessagesProcessedMetricAttributeKey specifies the key of an attribute for the queuewatch.messages.processed metric.
type QueuewatchMessagesProcessedMetricAttributeKey string

const (
	QueuewatchMessagesProcessedMetricAttributeKeyQueueName QueuewatchMessagesProcessedMetricAttributeKey = "queue.name"
)

// QueuewatchMessagesProcessedMetricConfig provides config for the queuewatch.messages.processed metric.
type QueuewatchMessagesProcessedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []QueuewatchMessagesProcessedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *QueuewatchMessagesProcessedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *QueuewatchMessagesProcessedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case QueuewatchMessagesProcessedMetricAttributeKeyQueueName:
		default:
			return fmt.Errorf("metric queuewatch.messages.processed doesn't have an attribute %v, valid attributes: [queue.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// QueuewatchQueueDepthMetricAttributeKey specifies the key of an attribute for the queuewatch.queue.depth metric.
type QueuewatchQueueDepthMetricAttributeKey string

const (
	QueuewatchQueueDepthMetricAttributeKeyQueueName QueuewatchQueueDepthMetricAttributeKey = "queue.name"
)

// QueuewatchQueueDepthMetricConfig provides config for the queuewatch.queue.depth metric.
type QueuewatchQueueDepthMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []QueuewatchQueueDepthMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *QueuewatchQueueDepthMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *QueuewatchQueueDepthMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case QueuewatchQueueDepthMetricAttributeKeyQueueName:
		default:
			return fmt.Errorf("metric queuewatch.queue.depth doesn't have an attribute %v, valid attributes: [queue.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for queuewatch metrics.
type MetricsConfig struct {
	QueuewatchMessagesProcessed QueuewatchMessagesProcessedMetricConfig `mapstructure:"queuewatch.messages.processed"`
	QueuewatchQueueDepth        QueuewatchQueueDepthMetricConfig        `mapstructure:"queuewatch.queue.depth"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		QueuewatchMessagesProcessed: QueuewatchMessagesProcessedMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []QueuewatchMessagesProcessedMetricAttributeKey{QueuewatchMessagesProcessedMetricAttributeKeyQueueName},
		},
		QueuewatchQueueDepth: QueuewatchQueueDepthMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []QueuewatchQueueDepthMetricAttributeKey{QueuewatchQueueDepthMetricAttributeKeyQueueName},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for queuewatch resource attributes.
type ResourceAttributesConfig struct {
	QueuewatchHost ResourceAttributeConfig `mapstructure:"queuewatch.host"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		QueuewatchHost: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for queuewatch metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
