// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/queuewatch component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("queuewatch")
	ScopeName = "github.com/apolzek/otel-collector-contrib-journey/day16/queuewatchreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
